Temporarily commenting out test run step in unit-tests.yml for cache testing.

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -18,14 +18,12 @@ on:
 
 env:
   AWS_CPP_SDK_VERSION: "1.9.365"
-  CCACHE_DIR: "/tmp/ccache"
   DEBIAN_FRONTEND: "noninteractive"
   KUBERNETES_VERSION: "1.24.3"
   HELM_VERSION: "3.8.1"
   MINIKUBE_VERSION: "1.26.1"
   OPENTELEMETRY_VERSION: "1.6.1"
   PYTHON_VERSION: "3.10"
-  SLATE_DISABLE_COMPILER_CACHE: False
 
 jobs:
   workflow-inputs:
@@ -115,61 +113,62 @@ jobs:
       - name: Build SLATE binaries
         working-directory: ./checkout/build
         run: |-
+          ls -al
           cmake .. -DBUILD_CLIENT=True -DBUILD_SERVER=True -DBUILD_SERVER_TESTS=True -DSTATIC_CLIENT=False
           export VERSION_OVERRIDE=localdev
-          make
+          make -j2 -k
+#
+#      - id: minikube
+#        name: Create Minikube Cluster
+#        uses: medyagh/setup-minikube@master
+#        with:
+#          minikube-version: ${{ env.MINIKUBE_VERSION }}
+#          driver: docker
+#          container-runtime: containerd
+#          kubernetes-version: "v${{ env.KUBERNETES_VERSION }}"
+#          cni: calico
+#
+#      - name: Download DynamoDB
+#        working-directory: .
+#        run: |-
+#          mkdir ./dynamodb
+#          echo "Downloading DynamoDB from Amazon......................."
+#          for FILENAME in dynamodb_local_latest.tar.gz dynamodb_local_latest.tar.gz.sha256
+#          do
+#            curl -fsSL https://s3.us-west-2.amazonaws.com/dynamodb-local/$FILENAME -o $FILENAME
+#          done
+#
+#          echo "Verifying download......................."
+#          sha256sum -c dynamodb_local_latest.tar.gz.sha256 || exit 1
+#
+#          echo "Extracting download archive......................."
+#          tar -zxf dynamodb_local_latest.tar.gz --directory ./dynamodb
+#          ls -al ./dynamodb
+#
+#      - name: Install Helm
+#        uses: azure/setup-helm@v3
+#        with:
+#          version: ${{ env.HELM_VERSION }}
 
-      - id: minikube
-        name: Create Minikube Cluster
-        uses: medyagh/setup-minikube@master
-        with:
-          minikube-version: ${{ env.MINIKUBE_VERSION }}
-          driver: docker
-          container-runtime: containerd
-          kubernetes-version: "v${{ env.KUBERNETES_VERSION }}"
-          cni: calico
-
-      - name: Download DynamoDB
-        working-directory: .
-        run: |-
-          mkdir ./dynamodb
-          echo "Downloading DynamoDB from Amazon......................."
-          for FILENAME in dynamodb_local_latest.tar.gz dynamodb_local_latest.tar.gz.sha256
-          do
-            curl -fsSL https://s3.us-west-2.amazonaws.com/dynamodb-local/$FILENAME -o $FILENAME
-          done
-
-          echo "Verifying download......................."
-          sha256sum -c dynamodb_local_latest.tar.gz.sha256 || exit 1
-
-          echo "Extracting download archive......................."
-          tar -zxf dynamodb_local_latest.tar.gz --directory ./dynamodb
-          ls -al ./dynamodb
-
-      - name: Install Helm
-        uses: azure/setup-helm@v3
-        with:
-          version: ${{ env.HELM_VERSION }}
-
-      - name: Run tests
-        timeout-minutes: 90
-        working-directory: ./checkout/build
-        env:
-          DYNAMODB_JAR: "${{ github.workspace }}/dynamodb/DynamoDBLocal.jar"
-          DYNAMODB_LIB: "${{ github.workspace }}/dynamodb/DynamoDBLocal_lib"
-          SLATE_SCHEMA_DIR: "${{ github.workspace }}/checkout/resources/api_specification"
-          TEST_SRC: "${{ github.workspace }}/checkout/test"
-        run: make check
-
-  notifications:
-    name: Notifications
-    runs-on: ubuntu-20.04
-    needs:
-      - test
-    if: ${{ always() && (needs.build.result == 'failure' || needs.test.result == 'failure') }}
-
-    steps:
-      - name: Notify Slack of Failure
-        uses: slateci/github-actions/.github/actions/slack-notify-failure@v11
-        with:
-          slack_bot_token: '${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}'
+#      - name: Run tests
+#        timeout-minutes: 90
+#        working-directory: ./checkout/build
+#        env:
+#          DYNAMODB_JAR: "${{ github.workspace }}/dynamodb/DynamoDBLocal.jar"
+#          DYNAMODB_LIB: "${{ github.workspace }}/dynamodb/DynamoDBLocal_lib"
+#          SLATE_SCHEMA_DIR: "${{ github.workspace }}/checkout/resources/api_specification"
+#          TEST_SRC: "${{ github.workspace }}/checkout/test"
+#        run: make check
+#
+#  notifications:
+#    name: Notifications
+#    runs-on: ubuntu-20.04
+#    needs:
+#      - test
+#    if: ${{ always() && (needs.build.result == 'failure' || needs.test.result == 'failure') }}
+#
+#    steps:
+#      - name: Notify Slack of Failure
+#        uses: slateci/github-actions/.github/actions/slack-notify-failure@v11
+#        with:
+#          slack_bot_token: '${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}'
